language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.8"
  - "3.9"
  - "3.9-dev"  # 3.9 development branch
  - "nightly"  # nightly build
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install .
env:
  - DJANGO_VERSION=4.0.2
  - DJANGO_VERSION=2.1.13
  - DJANGO_VERSION=2.2.6
# command to run tests
script:
  - pytest
  - python manage.py test
  - pip install -q Django==$DJANGO_VERSION
  - python setup.py -q install